version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
  
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    networks:
      - postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api1:
    build:
      context: .
      dockerfile: ./api_valor_do_metro_quadrado/Dockerfile
    environment:
      DB_NAME: api_db
      DB_USER: user
      DB_PASSWORD: pass
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "8081:8081"
    networks:
      - api1
      - api2
      - postgres
    depends_on:
      - postgres
      - api1_migration
  
  api1_migration:
    build:
      context: .
      dockerfile: ./api_valor_do_metro_quadrado/Dockerfile.migration
    environment:
      DB_NAME: api_db
      DB_USER: user
      DB_PASSWORD: pass
      DB_HOST: postgres
      DB_PORT: 5432
    command: bash -c "alembic upgrade head"
    networks:
      - postgres
    depends_on:
      - postgres
  
  api2:
    build:
      context: .
      dockerfile: ./api_valor_do_imovel/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - api2
      - postgres
    depends_on:
      - postgres

networks:
  api1:
  api2:
  postgres:

volumes:
  postgres-data: