FROM python:3.7-slim

WORKDIR /app

COPY ./api_valor_do_metro_quadrado/infrastructure ./infrastructure

COPY ./api_valor_do_metro_quadrado/alembic.ini .

RUN pip install --upgrade pip && pip install alembic psycopg2-binary
